const FILM_COUNT = 12;
const FILM_COUNT_PER_STEP = 5;
const MAX_COMMENTS_ON_FILM = 5;
const NOVICE_STATUS = 10;
const FAN_STATUS = 20;
const MOVIEBUFF_STATUS = 21;

export {
  FILM_COUNT,
  MAX_COMMENTS_ON_FILM,
  FILM_COUNT_PER_STEP,
  NOVICE_STATUS,
  FAN_STATUS,
  MOVIEBUFF_STATUS

};
